model:
  name: LiteratureCNN
  kernel_size: 3
  stride: 1
  learning_rate: 0.001
  schedule: scheduler
  optimizer: nadam
  loss_function: cross-entropy
  num_classes: 16
  input_shape: 533
training:
  batch_size: 64
  epochs: 43
  seed: 42
dataset:
  filename: C:\Users\nxf93627\PQD Classifier\data\16pqd_2000pattern_60hz_10cycle_withNoise.mat
  seed_random: 42
  test_percentage: 0.1
